package ir.nivora.app

import android.app.*
import android.content.*
import android.graphics.Color
import android.net.VpnService
import android.os.*
import android.text.InputType
import android.view.*
import android.widget.*
import ir.nivora.app.data.*
import ir.nivora.app.vpn.NivoraVpnService
import java.net.InetSocketAddress
import java.net.Socket
import java.text.NumberFormat
import java.util.Locale

class MainActivity:Activity(){
 private val api=ApiClient(BuildConfig.API_BASE_URL);private val main=Handler(Looper.getMainLooper());private val session by lazy{getSharedPreferences("session",0)};private val vpn by lazy{getSharedPreferences("vpn",0)};private val money=NumberFormat.getNumberInstance(Locale.forLanguageTag("fa-IR"));private var selectedUrl:String?=null
 private val vpnReceiver=object:BroadcastReceiver(){override fun onReceive(context:Context?,intent:Intent?){if(session.getString("token",null)!=null)main.postDelayed({load()},2500)}}
 override fun onCreate(state:Bundle?){super.onCreate(state);registerReceiver(vpnReceiver,IntentFilter("ir.nivora.app.VPN_STATE"),RECEIVER_NOT_EXPORTED);if(vpn.getString("state","")=="connected"&&!NivoraVpnService.isCoreRunning())vpn.edit().putString("state","disconnected").apply();if(session.getString("token",null)==null)login() else load()}
 override fun onDestroy(){unregisterReceiver(vpnReceiver);super.onDestroy()}
 private fun root()=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(40,40,40,40);gravity=Gravity.CENTER_HORIZONTAL;layoutDirection=View.LAYOUT_DIRECTION_RTL;setBackgroundColor(Color.rgb(244,248,246))}
 private fun wide()=LinearLayout.LayoutParams(-1,-2).apply{setMargins(0,8,0,8)}
 private fun input(h:String,pass:Boolean=false)=EditText(this).apply{hint=h;textSize=17f;if(pass)inputType=InputType.TYPE_CLASS_TEXT or InputType.TYPE_TEXT_VARIATION_PASSWORD}
 private fun text(s:String,size:Float=16f)=TextView(this).apply{text=s;textSize=size;setTextColor(Color.rgb(18,50,40));setPadding(4,8,4,8)}
 private fun button(s:String,fn:()->Unit)=Button(this).apply{text=s;setTextColor(Color.rgb(3,45,32));setBackgroundColor(Color.rgb(42,220,160));setOnClickListener{fn()}}
 private fun login(message:String=""){val b=root();b.addView(text("Nivora",30f));b.addView(text("ورود به حساب مشتری"));val p=input("شماره موبایل");val w=input("رمز عبور",true);val e=text(message).apply{setTextColor(Color.RED)};listOf(p,w,e).forEach{b.addView(it,wide())};b.addView(button("ورود"){bg({api.login(p.text.toString(),w.text.toString())},{session.edit().putString("token",it.token).apply();load()},{e.text=friendly(it)})},wide());b.addView(button("ساخت حساب جدید"){register()},wide());b.addView(button("بازیابی رمز عبور"){recovery(p.text.toString())},wide());setContentView(b)}
 private fun register(){val b=root();b.addView(text("ساخت حساب Nivora",28f));val n=input("نام و نام خانوادگی");val p=input("شماره موبایل");val w=input("رمز عبور (حداقل ۸ کاراکتر)",true);val e=text("").apply{setTextColor(Color.RED)};listOf(n,p,w,e).forEach{b.addView(it,wide())};b.addView(button("ثبت‌نام"){bg({api.register(n.text.toString(),p.text.toString(),w.text.toString())},{session.edit().putString("token",it.token).apply();load()},{e.text=friendly(it)})},wide());b.addView(button("بازگشت"){login()},wide());setContentView(b)}
 private fun recovery(initial:String){val p=input("شماره موبایل").apply{setText(initial)};AlertDialog.Builder(this).setTitle("بازیابی رمز عبور").setMessage("درخواست برای مدیریت ارسال می‌شود و بعد از احراز هویت رمز تازه دریافت می‌کنید.").setView(p).setPositiveButton("ثبت درخواست"){_,_->bg({api.requestPasswordReset(p.text.toString());true},{toast("درخواست بازیابی ثبت شد")},{toast(friendly(it))})}.setNegativeButton("انصراف",null).show()}
 private fun load(){val b=root();b.addView(ProgressBar(this));setContentView(b);val t=session.getString("token","")!!;bg({api.account(t) to api.plans()},{home(it.first,it.second)},{if(it.message=="UNAUTHORIZED"){session.edit().clear().apply();login("نشست ورود منقضی شده؛ دوباره وارد شوید.")}else loadError(friendly(it))})}
 private fun loadError(message:String){val b=root();b.addView(text("ارتباط موقتاً برقرار نشد",24f));b.addView(text(message),wide());b.addView(button("تلاش دوباره"){load()},wide());b.addView(button("خروج از حساب"){session.edit().clear().apply();login()},wide());setContentView(b)}
 private fun home(a:Account,plans:List<Plan>){val scroll=ScrollView(this);val b=root().apply{gravity=Gravity.TOP};val token=session.getString("token","")!!;b.addView(text("سلام ${a.name}",27f));b.addView(text("موجودی کیف پول: ${money.format(a.balanceToman)} تومان"),wide());b.addView(button("شارژ کیف پول"){topup(token)},wide());b.addView(text("اشتراک‌های من",23f));val active=a.subscriptions.filter{it.url!=null&&it.status=="active"};if(active.isEmpty())b.addView(text("هنوز اشتراک فعالی ندارید."))
  active.forEachIndexed{i,s->if(selectedUrl==null)selectedUrl=s.url;val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,20,24,20);setBackgroundColor(Color.WHITE);addView(text("${s.planName}${s.locationName?.let{" · $it"}?:""}",20f));addView(text(if(s.startsOnFirstUse)"زمان: از اولین اتصال محاسبه می‌شود" else "زمان باقی‌مانده: ${s.remainingDays} روز"));addView(text("مصرف: ${gb(s.usedBytes)} از ${gb(s.totalBytes)} گیگابایت · ${s.usagePercent}٪"));addView(ProgressBar(this@MainActivity,null,android.R.attr.progressBarStyleHorizontal).apply{max=1000;progress=(s.usagePercent*10).toInt()});addView(button(if(selectedUrl==s.url)"اشتراک انتخاب‌شده" else "انتخاب برای اتصال"){selectedUrl=s.url;home(a,plans)},wide());addView(button("کپی لینک اشتراک"){copy(s.url!!);toast("لینک کپی شد")},wide());addView(button("تمدید همین اشتراک"){confirmRenew(token,s)},wide())};b.addView(c,wide())}
  val state=vpn.getString("state","disconnected");b.addView(text("وضعیت اتصال: ${when(state){"connected"->"متصل";"error"->"خطا: ${vpn.getString("error","")}";else->"قطع"}}"));b.addView(button(if(state=="connected")"قطع اتصال" else "اتصال امن"){if(state=="connected")startService(Intent(this,NivoraVpnService::class.java).setAction(NivoraVpnService.ACTION_STOP)) else prepareVpn()},wide());b.addView(button("تست پینگ سرور"){ping()},wide());b.addView(text("خرید اشتراک",23f));plans.forEach{p->val c=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(24,20,24,20);setBackgroundColor(Color.WHITE);addView(text("${p.name}\n${p.trafficGb} گیگ · ${p.durationDays} روز · ${p.deviceLimit} دستگاه\n${money.format(p.priceToman)} تومان"));addView(button("خرید و ساخت فوری"){AlertDialog.Builder(this@MainActivity).setTitle("تأیید خرید").setMessage("${money.format(p.priceToman)} تومان از کیف پول کم می‌شود.").setPositiveButton("خرید"){_,_->bg({api.purchase(token,p.id)},{toast("اشتراک ساخته شد");load()},{toast(friendly(it))})}.setNegativeButton("انصراف",null).show()},wide())};b.addView(c,wide())};b.addView(button("خروج"){session.edit().clear().apply();login()},wide());scroll.addView(b);setContentView(scroll)}
 private fun topup(token:String){bg({api.cards()},{cards->val amount=input("مبلغ به تومان").apply{inputType=2};val ref=input("شماره پیگیری واریز");val v=LinearLayout(this).apply{orientation=LinearLayout.VERTICAL;setPadding(30,0,30,0);cards.forEach{addView(text("${it.number.chunked(4).joinToString("  ")}\n${it.holder}${it.bank?.let{b->" · $b"}?:""}"));addView(button("کپی شماره کارت"){copy(it.number)},wide())};addView(amount);addView(ref)};AlertDialog.Builder(this).setTitle("شارژ کیف پول").setView(v).setPositiveButton("ارسال برای تأیید"){_,_->bg({api.topup(token,amount.text.toString().toInt(),ref.text.toString())},{toast("درخواست شارژ ثبت شد")},{toast(friendly(it))})}.setNegativeButton("انصراف",null).show()},{toast(friendly(it))})}
 private fun confirmRenew(token:String,s:Subscription){AlertDialog.Builder(this).setTitle("تمدید ${s.planName}").setMessage("هزینه پلن از کیف پول کم و حجم و زمان به همین اشتراک افزوده می‌شود.").setPositiveButton("تمدید"){_,_->bg({api.renew(token,s.id)},{toast("تمدید انجام شد");load()},{toast(friendly(it))})}.setNegativeButton("انصراف",null).show()}
 private fun ping(){toast("در حال اندازه‌گیری…");bg({val start=System.nanoTime();Socket().use{it.connect(InetSocketAddress("edge.nivorali.com",8443),5000)};((System.nanoTime()-start)/1_000_000)},{toast("پینگ سرور: $it میلی‌ثانیه")},{toast("سرور پاسخ نداد")})}
 private fun prepareVpn(){if(selectedUrl==null){toast("ابتدا یک اشتراک فعال انتخاب کنید");return};val i=VpnService.prepare(this);if(i!=null)startActivityForResult(i,91)else startVpn()}
 override fun onActivityResult(r:Int,c:Int,d:Intent?){super.onActivityResult(r,c,d);if(r==91&&c==RESULT_OK)startVpn()}
 private fun startVpn(){startForegroundService(Intent(this,NivoraVpnService::class.java).putExtra(NivoraVpnService.EXTRA_URL,selectedUrl));toast("در حال برقراری اتصال…")}
 private fun gb(v:Long)=String.format(Locale.US,"%.1f",v/1073741824.0);private fun copy(v:String){(getSystemService(CLIPBOARD_SERVICE) as ClipboardManager).setPrimaryClip(ClipData.newPlainText("Nivora",v))};private fun toast(v:String)=Toast.makeText(this,v,Toast.LENGTH_LONG).show()
 private fun friendly(e:Throwable)=when(e.message){"INVALID_CREDENTIALS"->"شماره یا رمز عبور صحیح نیست";"PHONE_ALREADY_EXISTS"->"این شماره قبلاً ثبت شده";"WEAK_PASSWORD"->"رمز باید حداقل ۸ کاراکتر باشد";"INSUFFICIENT_BALANCE"->"موجودی کیف پول کافی نیست";"NO_CAPACITY"->"ظرفیت این پلن تکمیل است";else->e.message?:"خطا در ارتباط"}
 private fun <T> bg(work:()->T,ok:(T)->Unit,fail:(Throwable)->Unit)=Thread{runCatching(work).onSuccess{main.post{ok(it)}}.onFailure{main.post{fail(it)}}}.start()
}
