import test from 'node:test';
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {createApp} from '../src/app.js';
import {openDatabase} from '../src/db.js';
test('OpenVPN sale, private delivery, ownership and renewal through both panels',async t=>{
 const calls=[];
 const node=createServer(async(req,res)=>{let raw='';for await(const c of req)raw+=c;const b=JSON.parse(raw||'{}');calls.push({action:req.url,b});assert.equal(req.headers.authorization,'Bearer test-node-key');res.setHeader('content-type','application/json');res.end(JSON.stringify(req.url==='/profile'?{filename:'Nivora-test.ovpn',content:'client\nremote test 1194\n'}:{}));});
 await new Promise(r=>node.listen(0,'127.0.0.1',r));t.after(()=>node.close());
 const db=openDatabase(':memory:'),app=createServer(createApp(db,{adminToken:'test-admin'}));await new Promise(r=>app.listen(0,'127.0.0.1',r));t.after(()=>app.close());t.after(()=>db.close());
 const base='http://127.0.0.1:'+app.address().port,admin={authorization:'Bearer test-admin','content-type':'application/json'};
 async function request(path,body,headers=admin,expected=200){const r=await fetch(base+path,{method:body===undefined?'GET':'POST',headers,body:body===undefined?undefined:JSON.stringify(body)});const result=await r.json();assert.equal(r.status,expected,JSON.stringify(result));return result;}
 const panel=await request('/api/admin/panel-nodes',{name:'OpenVPN test',panelType:'openvpn',baseUrl:'http://127.0.0.1:'+node.address().port,apiToken:'test-node-key'},admin,201);
 const health=await request(`/api/admin/panel-nodes/${panel.id}/test`,{});assert.equal(health.status,'online');assert.equal(health.httpStatus,200);
 const location=await request('/api/admin/locations',{name:'فنلاند تست',countryCode:'FI',panelType:'openvpn',panelNodeId:panel.id},admin,201);
 const plan=await request('/api/admin/plans',{name:'OpenVPN تست',priceIrr:150000,trafficGb:30,durationDays:30,deviceLimit:1},admin,201);
 await request('/api/admin/locations/'+location.id+'/plans',{planIds:[plan.id]});
 const customer=await request('/api/admin/accounts',{name:'مشتری آزمایشی',phone:'09120000101',role:'customer',password:'password-123'},admin,201);
 const seller=await request('/api/admin/accounts',{name:'همکار آزمایشی',phone:'09120000102',role:'reseller',password:'password-123'},admin,201);
 const other=await request('/api/admin/accounts',{name:'همکار دیگر',phone:'09120000103',role:'reseller',password:'password-123'},admin,201);
 const login=async(a)=>({authorization:'Bearer '+(await request('/api/reseller/login',{phone:a.phone,password:'password-123'})).token,'content-type':'application/json'});
 const sellerAuth=await login(seller),otherAuth=await login(other);
 const sale=await request('/api/admin/sales',{customerId:customer.id,planId:plan.id},admin,201);
 assert.equal(calls.filter(c=>c.action==='/create').length,1);
 const delivered=await request(`/api/admin/orders/${sale.orderId}/ios-import`,{});
 assert.equal(delivered.protocol,'openvpn');assert.equal(delivered.filename,'Nivora-test.ovpn');
 await request(`/api/reseller/orders/${sale.orderId}/openvpn`,{},sellerAuth,404);
 const visible=await request('/api/plans');assert.equal(visible.some(p=>p.id===plan.id),false);
 await request('/api/admin/accounts/'+seller.id+'/wallet',{amountToman:500000},admin,201);
 const partnerSale=await request('/api/reseller/purchase',{customerAccountId:customer.id,planId:plan.id},sellerAuth,201);
 await request(`/api/reseller/orders/${partnerSale.orderId}/openvpn`,{},otherAuth,404);
 assert.equal((await request(`/api/reseller/orders/${partnerSale.orderId}/ios-import`,{},sellerAuth)).protocol,'openvpn');
 await request(`/api/reseller/orders/${partnerSale.orderId}/suspend`,{reason:'تعلیق آزمایشی'},sellerAuth);
 await request(`/api/reseller/orders/${partnerSale.orderId}/openvpn`,{},sellerAuth,409);
 await request(`/api/reseller/orders/${partnerSale.orderId}/resume`,{},sellerAuth);
 await request(`/api/reseller/orders/${partnerSale.orderId}/renew`,{},sellerAuth,201);
 assert.ok(calls.find(c=>c.action==='/renew')?.b.operationId.startsWith('renew:'));
 const rows=await request('/api/reseller/orders',undefined,sellerAuth);assert.equal(rows.find(o=>o.id===partnerSale.orderId).protocol,'openvpn');
 assert.equal(rows.find(o=>o.id===partnerSale.orderId).subscription_url,null);
});
