#!/usr/bin/env bash
set -Eeuo pipefail
APP_DIR=/opt/nivora
SERVICE=nivora.service
need_root(){ [[ ${EUID:-$(id -u)} -eq 0 ]] || { echo "Run with sudo"; exit 1; }; }
status(){ systemctl status "$SERVICE" --no-pager; }
logs(){ journalctl -u "$SERVICE" -n "${2:-100}" --no-pager; }
backup(){ sudo -u nivora bash -lc "cd '$APP_DIR' && /usr/bin/node scripts/backup.js"; }
recovery_export(){ need_root; bash "${APP_DIR}/scripts/export-recovery-bundle.sh" "${2:-$APP_DIR/backups}"; }
recovery_import(){ need_root; [[ -n "${2:-}" ]] || { echo "Usage: nivora recovery-import /path/nivora-recovery-*.tar.gz"; exit 1; }; systemctl stop "$SERVICE"; bash "${APP_DIR}/scripts/import-recovery-bundle.sh" "$2"; systemctl start "$SERVICE"; }
update(){ need_root; cd "$APP_DIR"; git -c safe.directory="$APP_DIR" fetch --tags origin; local target=${2:-$(git -c safe.directory="$APP_DIR" tag --sort=-v:refname | head -n1)}; [[ -n "$target" ]] || target=origin/main; git -c safe.directory="$APP_DIR" checkout "$target"; npm ci --omit=dev; chown -R nivora:nivora "$APP_DIR"; install -m 0644 deploy/nivora-panel-stats.service /etc/systemd/system/nivora-panel-stats.service; install -m 0644 deploy/nivora-panel-stats.timer /etc/systemd/system/nivora-panel-stats.timer; systemctl daemon-reload; systemctl enable --now nivora-panel-stats.timer; systemctl start nivora-panel-stats.service; systemctl restart "$SERVICE"; for _ in {1..15}; do curl -fsS http://127.0.0.1:8787/health && { echo; return; }; sleep 1; done; systemctl status "$SERVICE" --no-pager; return 1; }
restore(){ need_root; [[ -n "${2:-}" ]] || { echo "Usage: nivora restore /path/backup.db"; exit 1; }; systemctl stop "$SERVICE"; cd "$APP_DIR"; DATABASE_PATH=./data/nivora.db /usr/bin/node scripts/restore-backup.js "$2" --force; chown -R nivora:nivora data; systemctl start "$SERVICE"; }
remove(){ need_root; read -rp "Type REMOVE-NIVORA to stop and remove the service (data is kept): " answer; [[ "$answer" == REMOVE-NIVORA ]] || exit 1; systemctl disable --now "$SERVICE" nivora-backup.timer nivora-panel-stats.timer; rm -f /etc/systemd/system/nivora.service /etc/systemd/system/nivora-backup.service /etc/systemd/system/nivora-backup.timer /etc/systemd/system/nivora-panel-stats.service /etc/systemd/system/nivora-panel-stats.timer /usr/local/bin/nivora; systemctl daemon-reload; echo "Service removed. Data remains in $APP_DIR/data and $APP_DIR/backups"; }
admin_user(){ need_root; read -rp "Admin username [admin]: " username; username=${username:-admin}; [[ "$username" =~ ^[A-Za-z0-9_.-]{3,40}$ ]] || { echo "Invalid username"; exit 1; }; read -rsp "New admin password (min 8 chars): " password; echo; read -rsp "Repeat password: " repeat; echo; [[ "$password" == "$repeat" ]] || { echo "Passwords do not match"; exit 1; }; [[ ${#password} -ge 8 ]] || { echo "Password is too short"; exit 1; }; result=$(printf '%s' "$password" | /usr/bin/node "$APP_DIR/scripts/hash-admin-password.mjs"); unset password repeat; salt=${result%%:*}; hash=${result#*:}; tmp=$(mktemp "$APP_DIR/.env.admin.XXXXXX"); awk '!/^ADMIN_USERNAME=|^ADMIN_PASSWORD_SALT=|^ADMIN_PASSWORD_HASH=/' "$APP_DIR/.env" > "$tmp"; printf '\nADMIN_USERNAME=%s\nADMIN_PASSWORD_SALT=%s\nADMIN_PASSWORD_HASH=%s\n' "$username" "$salt" "$hash" >> "$tmp"; chown nivora:nivora "$tmp"; chmod 600 "$tmp"; mv "$tmp" "$APP_DIR/.env"; systemctl restart "$SERVICE"; echo "Admin credentials updated."; }
case "${1:-menu}" in status) status;; logs) logs "$@";; backup) backup;; recovery-export) recovery_export "$@";; recovery-import) recovery_import "$@";; update) update "$@";; restore) restore "$@";; restart) need_root; systemctl restart "$SERVICE"; status;; admin-user) admin_user;; remove) remove;; menu) echo "nivora {status|logs|backup|recovery-export [DIR]|recovery-import FILE|update [version]|restore FILE|restart|admin-user|remove}";; *) echo "Unknown command"; exit 1;; esac
