import { hashPassword } from './auth.js';

const normalizePhone=value=>String(value||'').replace(/[^\d+]/g,'').replace(/^\+98/,'0').replace(/^0098/,'0');
export function createTelegramRecovery(db,{getConfig=()=>({token:process.env.TELEGRAM_BOT_TOKEN,secret:process.env.TELEGRAM_WEBHOOK_SECRET,enabled:true}),fetchImpl=fetch}={}){
  return async(req,res,readJson,json)=>{
    const {token,secret,enabled}=getConfig();
    if(!enabled||!token||!secret)return json(res,503,{error:'TELEGRAM_RECOVERY_DISABLED'});
    const send=async(chatId,text,extra={})=>{await fetchImpl(`https://api.telegram.org/bot${token}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:chatId,text,...extra})})};
    if(req.headers['x-telegram-bot-api-secret-token']!==secret)return json(res,401,{error:'UNAUTHORIZED'});
    const update=await readJson(req),message=update.message;if(!message?.chat?.id)return json(res,200,{ok:true});const chat=String(message.chat.id),now=new Date(),expires=new Date(now.getTime()+10*60_000).toISOString();
    if(message.text==='/start'||message.text==='بازیابی رمز'){db.prepare(`INSERT INTO telegram_recovery_sessions(chat_id,state,expires_at,created_at) VALUES(?,'waiting_contact',?,?) ON CONFLICT(chat_id) DO UPDATE SET account_id=NULL,verified_phone=NULL,state='waiting_contact',expires_at=excluded.expires_at`).run(chat,expires,now.toISOString());await send(chat,'برای احراز هویت، شماره‌ای را بفرستید که متعلق به همین حساب تلگرام است.',{reply_markup:{keyboard:[[{text:'ارسال شماره من',request_contact:true}]],resize_keyboard:true,one_time_keyboard:true}});return json(res,200,{ok:true});}
    if(message.contact){if(String(message.contact.user_id)!==String(message.from?.id)){await send(chat,'فقط شماره متعلق به حساب تلگرام خودتان پذیرفته می‌شود.');return json(res,200,{ok:true});}const phone=normalizePhone(message.contact.phone_number),account=db.prepare("SELECT id FROM accounts WHERE phone=? AND role='customer' AND status='active'").get(phone);if(!account){await send(chat,'حساب فعالی با این شماره پیدا نشد.');return json(res,200,{ok:true});}db.prepare(`INSERT INTO telegram_recovery_sessions(chat_id,account_id,verified_phone,state,expires_at,created_at) VALUES(?,?,?,'waiting_password',?,?) ON CONFLICT(chat_id) DO UPDATE SET account_id=excluded.account_id,verified_phone=excluded.verified_phone,state='waiting_password',expires_at=excluded.expires_at`).run(chat,account.id,phone,expires,now.toISOString());await send(chat,'شماره تأیید شد. رمز جدید با حداقل ۸ کاراکتر را ارسال کنید.',{reply_markup:{remove_keyboard:true}});return json(res,200,{ok:true});}
    const session=db.prepare("SELECT * FROM telegram_recovery_sessions WHERE chat_id=? AND state='waiting_password' AND expires_at>?").get(chat,now.toISOString());if(session&&message.text){let password;try{password=hashPassword(message.text)}catch{await send(chat,'رمز باید حداقل ۸ کاراکتر باشد.');return json(res,200,{ok:true});}db.prepare('UPDATE accounts SET password_hash=?,password_salt=?,updated_at=? WHERE id=?').run(password.hash,password.salt,now.toISOString(),session.account_id);db.prepare('DELETE FROM account_sessions WHERE account_id=?').run(session.account_id);db.prepare("UPDATE telegram_recovery_sessions SET state='complete' WHERE chat_id=?").run(chat);await send(chat,'رمز با موفقیت تغییر کرد. اکنون می‌توانید وارد اپ شوید.');}
    return json(res,200,{ok:true});
  };
}
