import { hashPassword } from './auth.js';
const phone=v=>String(v||'').replace(/[^\d+]/g,'').replace(/^\+98/,'0').replace(/^0098/,'0');
const menu={keyboard:[[{text:'👤 حساب من'},{text:'📦 اشتراک‌های من'}],[{text:'🔑 بازیابی رمز'},{text:'📥 دانلود برنامه'}],[{text:'☎️ پشتیبانی'}]],resize_keyboard:true};
const adminMenu={keyboard:[[{text:'📊 آمار مدیریت'},{text:'🧾 پرداخت‌های معلق'}],[{text:'🎫 تیکت‌های باز'},{text:'👥 مشتریان'}],[{text:'🛡 مدیریت'}]],resize_keyboard:true};
export function createTelegramRecovery(db,{getConfig,fetchImpl=fetch}={}){return async(req,res,readJson,json)=>{const c=getConfig();if(!c.enabled||!c.token||!c.secret)return json(res,503,{error:'TELEGRAM_RECOVERY_DISABLED'});if(req.headers['x-telegram-bot-api-secret-token']!==c.secret)return json(res,401,{error:'UNAUTHORIZED'});const send=(id,text,extra={})=>fetchImpl(`https://api.telegram.org/bot${c.token}/sendMessage`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({chat_id:id,text,...extra})});const u=await readJson(req),m=u.message;if(!m?.chat?.id)return json(res,200,{ok:true});const chat=String(m.chat.id),user=String(m.from?.id||''),now=new Date(),admin=c.adminIds.includes(user),link=db.prepare('SELECT l.*,a.name FROM telegram_account_links l JOIN accounts a ON a.id=l.account_id WHERE l.telegram_user_id=?').get(user);
if(admin&&(m.text==='/start'||m.text==='🛡 مدیریت')){const stats=db.prepare(`SELECT (SELECT COUNT(*) FROM accounts WHERE role='customer') customers,(SELECT COUNT(*) FROM orders WHERE status='under_review') pending,(SELECT COUNT(*) FROM subscriptions WHERE status='active') active`).get();await send(chat,`مدیریت Nivora\n\nمشتریان: ${stats.customers}\nپرداخت‌های معلق: ${stats.pending}\nاشتراک فعال: ${stats.active}`,{reply_markup:adminMenu});return json(res,200,{ok:true});}
if(admin&&m.text==='📊 آمار مدیریت'){const x=db.prepare(`SELECT COUNT(*) orders,COALESCE(SUM(amount_transferred_irr/10),0) sales FROM orders WHERE status='approved'`).get();await send(chat,`تعداد فروش: ${x.orders}\nفروش ثبت‌شده: ${x.sales.toLocaleString('fa-IR')} تومان`);return json(res,200,{ok:true});}
if(admin&&m.text==='🧾 پرداخت‌های معلق'){const rows=db.prepare(`SELECT customer_name,phone,amount_transferred_irr FROM orders WHERE status='under_review' ORDER BY created_at DESC LIMIT 10`).all();await send(chat,rows.length?rows.map(x=>`${x.customer_name} | ${x.phone} | ${Math.round((x.amount_transferred_irr||0)/10).toLocaleString('fa-IR')} تومان`).join('\n'):'پرداخت معلقی وجود ندارد.');return json(res,200,{ok:true});}
if(admin&&m.text==='🎫 تیکت‌های باز'){const rows=db.prepare(`SELECT t.subject,a.name FROM support_tickets t JOIN accounts a ON a.id=t.account_id WHERE t.status<>'closed' ORDER BY t.updated_at DESC LIMIT 10`).all();await send(chat,rows.length?rows.map(x=>`${x.name} — ${x.subject}`).join('\n'):'تیکت بازی وجود ندارد.',{reply_markup:adminMenu});return json(res,200,{ok:true});}
if(admin&&m.text==='👥 مشتریان'){const stats=db.prepare(`SELECT COUNT(*) total,SUM(CASE WHEN status='active' THEN 1 ELSE 0 END) active FROM accounts WHERE role='customer'`).get();await send(chat,`کل مشتریان: ${stats.total||0}\nحساب فعال: ${stats.active||0}`,{reply_markup:adminMenu});return json(res,200,{ok:true});}
if(admin){await send(chat,'شما به‌عنوان مدیر شناسایی شدید. یکی از گزینه‌های مدیریت را انتخاب کنید.',{reply_markup:adminMenu});return json(res,200,{ok:true});}
if(m.text==='📥 دانلود برنامه'){if(!c.latestReleaseUrl){await send(chat,'لینک نسخه جدید هنوز توسط مدیریت منتشر نشده است.',{reply_markup:menu});return json(res,200,{ok:true});}await send(chat,'آخرین نسخه رسمی Nivora آماده دانلود است.',{reply_markup:{inline_keyboard:[[{text:'📥 دانلود آخرین نسخه',url:c.latestReleaseUrl}]]}});return json(res,200,{ok:true});}
if((m.text==='/start'||m.text==='🔑 بازیابی رمز')&&!link){await send(chat,'برای اتصال امن حساب، شماره متعلق به همین حساب تلگرام را ارسال کنید.',{reply_markup:{keyboard:[[{text:'📱 ارسال شماره من',request_contact:true}]],resize_keyboard:true,one_time_keyboard:true}});return json(res,200,{ok:true});}
if(m.contact){if(String(m.contact.user_id)!==user){await send(chat,'فقط شماره حساب تلگرام خودتان پذیرفته می‌شود.');return json(res,200,{ok:true});}const p=phone(m.contact.phone_number),a=db.prepare("SELECT id,name FROM accounts WHERE phone=? AND role='customer' AND status='active'").get(p);if(!a){await send(chat,'حساب فعالی با این شماره پیدا نشد.');return json(res,200,{ok:true});}db.prepare(`INSERT INTO telegram_account_links(telegram_user_id,chat_id,account_id,phone,linked_at,last_seen_at) VALUES(?,?,?,?,?,?) ON CONFLICT(telegram_user_id) DO UPDATE SET chat_id=excluded.chat_id,account_id=excluded.account_id,phone=excluded.phone,last_seen_at=excluded.last_seen_at`).run(user,chat,a.id,p,now.toISOString(),now.toISOString());await send(chat,`حساب ${a.name} با موفقیت متصل شد.`,{reply_markup:menu});return json(res,200,{ok:true});}
if(!link){await send(chat,'ابتدا /start را بزنید و شماره خودتان را تأیید کنید.');return json(res,200,{ok:true});}
if(m.text==='👤 حساب من'){const w=db.prepare('SELECT balance_toman FROM wallet_accounts WHERE account_id=?').get(link.account_id);await send(chat,`${link.name}\n${link.phone}\nموجودی: ${(w?.balance_toman||0).toLocaleString('fa-IR')} تومان`,{reply_markup:menu});}
else if(m.text==='📦 اشتراک‌های من'){const rows=db.prepare(`SELECT p.name,s.status,s.subscription_url FROM orders o JOIN plans p ON p.id=o.plan_id JOIN subscriptions s ON s.order_id=o.id WHERE o.account_id=? AND o.order_kind='purchase' ORDER BY o.created_at DESC LIMIT 10`).all(link.account_id);await send(chat,rows.length?rows.map(x=>`${x.name} — ${x.status}${x.subscription_url?`\n${x.subscription_url}`:''}`).join('\n\n'):'اشتراکی ندارید.',{reply_markup:menu});}
else if(m.text==='🔑 بازیابی رمز'){db.prepare(`INSERT INTO telegram_recovery_sessions(chat_id,account_id,verified_phone,state,expires_at,created_at) VALUES(?,?,?,'waiting_password',?,?) ON CONFLICT(chat_id) DO UPDATE SET account_id=excluded.account_id,verified_phone=excluded.verified_phone,state='waiting_password',expires_at=excluded.expires_at`).run(chat,link.account_id,link.phone,new Date(now.getTime()+600000).toISOString(),now.toISOString());await send(chat,'رمز جدید با حداقل ۸ کاراکتر را ارسال کنید.',{reply_markup:{remove_keyboard:true}});}
else{const s=db.prepare("SELECT * FROM telegram_recovery_sessions WHERE chat_id=? AND state='waiting_password' AND expires_at>?").get(chat,now.toISOString());if(s){let p;try{p=hashPassword(m.text)}catch{await send(chat,'رمز باید حداقل ۸ کاراکتر باشد.');return json(res,200,{ok:true});}db.prepare('UPDATE accounts SET password_hash=?,password_salt=?,updated_at=? WHERE id=?').run(p.hash,p.salt,now.toISOString(),s.account_id);db.prepare('DELETE FROM account_sessions WHERE account_id=?').run(s.account_id);db.prepare("UPDATE telegram_recovery_sessions SET state='complete' WHERE chat_id=?").run(chat);await send(chat,'رمز تغییر کرد.',{reply_markup:menu});}else await send(chat,'یکی از گزینه‌های منو را انتخاب کنید.',{reply_markup:menu});}return json(res,200,{ok:true});};}
