apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'

android {
    namespace 'ir.nivora.app'
    compileSdk 36
    defaultConfig {
        applicationId 'ir.nivora.app'
        minSdk 26
        targetSdk 36
        versionCode 12
        versionName '0.4.9'
        def apiUrl = providers.gradleProperty('NIVORA_API_BASE_URL').getOrElse('https://b.nivorali.com')
        buildConfigField 'String', 'API_BASE_URL', '"' + apiUrl + '"'
    }
    buildTypes { release { minifyEnabled true; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro' } }
    compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
    kotlinOptions { jvmTarget = '17' }
    buildFeatures { buildConfig true }
}

dependencies { implementation files('libs/libXray-26.7.28.aar') }
